### ISSUE TITLE
Define Agile/SDLC pathways image

### ISSUE THREAD

**Issue by linuxwebexpert** [vta/devops#1]
|#350 - https://projects.vta.org/projects/devops-server/work_packages/350/activity

# Feature Request
The Agile/SDLC pathways image does not provide descriptions and references

# Suggestion
Add industry-standards and best practices hyperlinks and concise descriptions
Simple explain each image in order of pathway connections

# Tasks
- [x] Create PNG for every image within SVG original
- [x] Define descriptions to explain each section of pathway connections
- [x] Provide hyperlinks to available documentation references
